#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xF2FC4E45883BCBA4 (Martin.Vierula@trustwave.com)
#
Name     : modsecurity-nginx
Version  : 1.0.3
Release  : 26
URL      : https://github.com/SpiderLabs/ModSecurity-nginx/releases/download/v1.0.3/modsecurity-nginx-v1.0.3.tar.gz
Source0  : https://github.com/SpiderLabs/ModSecurity-nginx/releases/download/v1.0.3/modsecurity-nginx-v1.0.3.tar.gz
Source1  : https://github.com/SpiderLabs/ModSecurity-nginx/releases/download/v1.0.3/modsecurity-nginx-v1.0.3.tar.gz.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: modsecurity-nginx-lib = %{version}-%{release}
BuildRequires : buildreq-nginx
BuildRequires : modsecurity-dev
BuildRequires : openssl-dev

%description
<img src="https://github.com/SpiderLabs/ModSecurity/raw/v3/master/others/modsec.png" width="50%">

%package lib
Summary: lib components for the modsecurity-nginx package.
Group: Libraries

%description lib
lib components for the modsecurity-nginx package.


%prep
%setup -q -n modsecurity-nginx-v1.0.3
cd %{_builddir}/modsecurity-nginx-v1.0.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
nginx-module configure
nginx-module build

%install
nginx-module install %{buildroot}


%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/nginx-mainline/ngx_http_modsecurity_module.so
